### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by matjazpotocnik** [robertweiss/PromptChatGPT#1]
Hi Robert, thanks for the module! I was playing with it and thougtht it would be good to check for response results from ChatGPT:
in this line: `$result = $this->chatGPT->chat($chat);` $result could be false and then you get errors from json_decode() and accessing the json data.

**Comment by robertweiss** [comment]
You’re absolutely right, the module is still in an early state and far from bulletproof 😄 I added some error handling to the getAnswer-method.
